apiVersion: app/v1
metadata:
  name: chetana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Chetana2403/my-argocd-app
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true