apiVersion: apps
kind: Ddeployment
metadata:
  name: my-app
  labels:
    app:nginx
spec:
  replicas:2
  selector:
    matchLabels:
      app:nginx
  template:
    metadata:
      labels:
        app:nginx
    spec:
      containers:
      - name: nginx
        image: nginx-latest
        pots:
        - containerPort: 80